### ISSUE TITLE
Turingmachine

### ISSUE THREAD

**Issue by kaldimartin** [Teaching-projects/SZE-FoNyA-2021-fixed-TM#1]
Tisztelt Tanár Úr!

Végül Pythonban oldottam meg a turing gépet, egy olyat csináltam, ami hozzáad 1-et az inputhoz. Egyelőre így állok vele, feltöltöttem.

**Comment by hegyhati** [comment]
Hat mosti lyen 3/4 allok. Ugye altalanos a Turing geped, a main-ben inicializalod konkretan az eggyel novelo valamire. Jo lenne felhuzni 4-re. Tkinterrel valami egyszeru GUI-t melletenni kb fel ora munka. Illetve mivel igy csinaltad meg a TM-et, siman ki tudsz menteni TM-eket json-be, meg onnet visszarantani akar. No, mindegy, csak otletelek itt fel 1-kor. 

Jah, kiprobalni amugy nem tudtam, milyen python configgal dolgozol Te? Nalam 3.6.9 van, szerintem amiatt nem szereti a `set[str]` dolgaidat.

**Comment by kaldimartin** [comment]
Nálam 3.9.5 van, akkor biztos amiatt. A Tkintert néztem én is, próbálkoztam is vele, csak kevés sikerrel. Munka mellett most nincs sok időm, így ha meg tudunk egyezni a 3-ban, nekem az is megfelelne.

**Comment by hegyhati** [comment]
Legyen 4, mashol is joszivu voltam.

**Comment by kaldimartin** [comment]
Rendben, köszönöm szépen!
